name: lcne_transcriptomics
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - scanpy
  - scvi-tools
  - anndata
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - scipy
  - pip
  - pip:
    - jupyter